services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: tahaexo
      POSTGRES_PASSWORD: secret
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always