import type { Metadata } from "next";
import "./globals.css";
import Logo from "components/Logo/Logo";
export const metadata: Metadata = {
  title: "ft_transcendence",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
    <body className="w-full bg-[url('../../public/wallpaper.png')] bg-no-repeat bg-cover min-h-screen bg-black">
        <div className="flex min-h-screen">
                <div className="hidden xs:block"> 
                    <Logo />
                </div>
                {children}
        </div>
    </body>
</html>
  );
}
