import type { Metadata } from "next";
import "./globals.css";
import Logo from "components/Logo/Logo";
import toast, { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "ft_transcendence",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full relative bg-black">
        <video
          autoPlay
          loop
          muted
          playsInline
          className="object-cover w-full h-full absolute top-0 left-0 z-0"
        >
          <source
            src="https://res.cloudinary.com/digeitq2e/video/upload/v1733753912/wabwszkn1x50lq9svbd3.mp4"
            type="video/mp4"
          />
        </video>
        <div className="absolute inset-0 bg-black/70 w-full h-full"></div>
        <div className="relative z-10">
          {children}
        <Toaster toastOptions={{
          className: '',
          style: {
            border: '2px solid violet',
            backgroundColor: 'darkviolet',
            color:'white'
          },
        }}/>
        </div>
      </body>
    </html>
  );
}
