version: '3.9'

networks:
  infra:
    name: astropong

services:
  # frontend:
  #   build: 
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   image: frontend:sa
  #   container_name: frontend
  #   volumes:
  #     - ../frontend/app:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - infra
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   restart: always

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    image: backend:sa
    container_name: backend
    volumes:
      - ../backend/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - infra
    healthcheck:
      test: ["CMD-SHELL", "python manage.py check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database:sa
    container_name: ${POSTGRES_HOST}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - infra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   expose:
  #     - "6379"
  #   env_file:
  #     - .env
  #   networks:
  #     - infra
  #   restart: always
